notesea/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework_nested import routers
from notes.views import NoteViewSet
from notes.views import FilteringNotesAPIView
from notesea.views import UserViewSet
from notesea.views import LoginView
from notesea.views import LogoutView
from notesea.views import IndexView

from notesea.views import published_note_detail
from notes.views import NoteViewInUUIdScopeSet

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)
router.register(r'notes', NoteViewSet)
router.register(r'notes-in-uuid-scope', NoteViewInUUIdScopeSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^published_notes/(?P<note_token>[0-9A-Za-z]{40})$', published_note_detail),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/auth/login/$', LoginView.as_view(), name='login'),
    url(r'^api/v1/auth/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/v1/filterednotes/', FilteringNotesAPIView.as_view(), name='filtered_notes'),
    url(r'^.*$', IndexView.as_view(), name='index')
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Max

class Note(models.Model):
    owner = models.ForeignKey(User, related_name='notes')
    title = models.CharField(max_length=140)
    content = models.TextField(null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    uuid = models.IntegerField()

    NOTICE = 'NO'
    REFERENCE = 'RE'
    PERSONAL_TODO = 'PT'
    JOTTING = 'JO'

    CATEGORY_CHOICES = (
        (NOTICE, 'Заметка'),
        (REFERENCE, 'Ссылка'),
        (PERSONAL_TODO, 'TODO'),
        (JOTTING, 'MEMO'),
    )

    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default=NOTICE)
    pub_token=models.CharField(max_length=40, null=True, blank=True)

    class Meta:
        ordering = ('-created_at',)

    def save(self, *args, **kwargs):
        if not self.pk:
            max_uuid_for_owner = self.owner.notes.aggregate(Max('uuid'))
            if max_uuid_for_owner['uuid__max']:
                self.uuid = max_uuid_for_owner['uuid__max'] + 1
            else:
                self.uuid = 1
        super(Note, self).save(*args, **kwargs)

notes/views.py
import string
import random
from datetime import datetime
from django.utils import dateparse, timezone

from rest_framework import permissions, viewsets
from rest_framework import generics

from notes.models import Note
from notes.serializers import NoteSerializer
from notes.permissions import IsOwnerOfNote

class NoteViewSet(viewsets.ModelViewSet):
    queryset = Note.objects.order_by('created_at')
    serializer_class = NoteSerializer
    permission_classes = (IsOwnerOfNote,)

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:
            return (permissions.AllowAny(),)
        return (permissions.IsAuthenticated(), IsOwnerOfNote(),)

    def get_queryset(self):
        queryset = Note.objects.filter(owner=self.request.user)
        return queryset

    def perform_create(self, serializer):
        instance = serializer.save(owner=self.request.user)

        return super(NoteViewSet, self).perform_create(instance)

    def perform_update(self, serializer):
        if serializer.is_valid():
            toggle_publish = self.request.query_params.get('togglepublish', None)
            if toggle_publish:
                if toggle_publish == 't':
                    token = self._get_publish_token()
                    while Note.objects.filter(pub_token=token).exists():
                        token = self._get_publish_token()
                    serializer.save(pub_token=token)
                else:
                    serializer.save(pub_token=None)
            else:
                serializer.save()

    def _get_publish_token(self):
        return ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.ascii_uppercase + string.digits) for _ in range(40))

class NoteViewInUUIdScopeSet(viewsets.ModelViewSet):
    serializer_class = NoteSerializer
    queryset = Note.objects.select_related('owner')
    lookup_field = 'uuid'

    def get_queryset(self):
        queryset = Note.objects.filter(owner=self.request.user)
        return queryset

class FilteringNotesAPIView(generics.ListAPIView):
    serializer_class = NoteSerializer
    POSSIBLE_ORDERED_COLUMNS = ['title', 'created_at', 'is_featured', 'category']

    def get_queryset(self):
        queryset = Note.objects.filter(owner=self.request.user)
        sort_param = self.request.query_params.get('sort', None)

        # Hardcoded solution
        # Create multilist for holding at least two items,
        # where
        #   first value is query parameter string
        #   second value is inserted filter for queryset
        #   third (optional) append time for date
        #       amint - append min time
        #       amaxt - append max time

        #  marked as FIXME!

        multifilteredFieldsPairs = []
        multifilteredFieldsPairs.append(['title','title__icontains'])
        multifilteredFieldsPairs.append(['startDate', 'created_at__gte', 'amint'])
        multifilteredFieldsPairs.append(['endDate', 'created_at__lte', 'amaxt'])
        multifilteredFieldsPairs.append(['category', 'category'])
        filter_dict = self._filter_populate(self.request.query_params, multifilteredFieldsPairs)


        sort_fields = None
        if sort_param:
            sort_fields = self._sort_populate(sort_param)

        if filter_dict:
            queryset = queryset.filter(**filter_dict)

        if sort_fields:
            queryset = queryset.order_by(*sort_fields)

        return queryset

    def _filter_populate(self, q_params, neededValues):
        result = {}
        for param in neededValues:
            perhaps_value = q_params.get(param[0], None)
            if perhaps_value:
                if len(param) > 2 and param[2] == 'amint':
                    result[param[1]] = datetime.combine(dateparse.parse_date(perhaps_value),datetime.min.time())
                elif len(param) > 2 and param[2] == 'amaxt':
                    result[param[1]] = datetime.combine(dateparse.parse_date(perhaps_value),datetime.max.time())
                else:
                    result[param[1]] = perhaps_value
        return result

    def _sort_populate(self, str_with_sequence_values, group_delimeter=';', pair_delimeter=':'):
        result = []
        got_parameters = str_with_sequence_values.split(group_delimeter)
        for parameter in got_parameters:
            parameter_with_order = parameter.split(pair_delimeter)
            descendig_direction = True if len(parameter_with_order) > 1 and parameter_with_order[1] == 'desc' else False
            if parameter_with_order[0] in self.POSSIBLE_ORDERED_COLUMNS:
                inserted_value = ('-' + parameter_with_order[0]) if descendig_direction else parameter_with_order[0]
                result.append(inserted_value)
        return result

templates/notes/pub-note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .public-note {
            margin: 0 auto;
            width: 50%;
        }
        .public-note > .title {
            color: red;
            font-size: 1.6em;
        }
        h3.title::first-letter {
            font-weight: bold;
            font-size: 1.9em;
            color: #8cae1a;
        }
        .public-note .public-note__content {
            margin: 26px 10px 54px -2px;
            color: #ae351d;
            font-size: 1.4em;
        }

        .public-note .public-note__info p {
            display: inline;
        }
        .public-note .public-note__info p:first-child {
            margin-right: 32px;
            border-bottom: 5px solid #44f412;
        }

        .public-note .public-note__info span:first-child {
            margin-right: 52px;
        }

        span {
            border: 2px dashed #f91203;
            margin-left: 8px;
            background-color: #91baec;
            -moz-border-radius: 26px 26px 26px 26px;
            border-radius: 26px 26px 26px 26px;
            padding: 10px 10px;
        }

        .public-note .public-note__info .public-note__created-at {
            font-size: 1.3em;
            color: #9517b2;

        }
        .public-note .public-note__info .featured {
            background-color: #02fead;
            color: #11043b;
        }
    </style>
</head>
<body>
    <div class="public-note">
        <h3 class="title">{{published_note.title}}</h3>
        <div class="public-note__content">
            <p>{{published_note.content}}</p>
        </div>

        <div class="public-note__info">
            <p class="public-note__created-at">{{ published_note.created_at | date:'d-m-Y' }}</p>
            <p>Категория:<span>{{published_note.get_category_display}}</span></p>
            {% if published_note.is_featured %}
                <span class="featured">Избранная</span>
            {% endif %}
        </div>

    </div>

</body>
</html>